version: "3.0"

services:
  laravel:
    build: ./laravel
    container_name: laravel
    restart: always
    depends_on:
      - database
    volumes:
      - ./laravel:/var/www/laravel
    networks:
      - batdongsan
  database:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
    volumes:
      - ./mysql/db:/var/lib/mysql
    networks:
      - batdongsan
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - database
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
    networks:
      - batdongsan
  nginx:
    container_name: nginx
    depends_on:
      - database
      - laravel
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./laravel/:/var/www/laravel/
    networks:
      - batdongsan
volumes:
    mysql:
networks:
  batdongsan:
    driver: bridge